project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "blog/index.qmd"
    - "blog/optimal-control-template/index.qmd"
    - "blog/optimization-workflow-template/index.qmd"
    - "project/index.qmd"
    - "project/casadi-constrained-mpc/index.qmd"
    - "project/mpc-project-template/index.qmd"
    - "talk/index.qmd"
    - "talk/train-control-talk-template/index.qmd"
    - "about/index.*md"
    - "colophon/index.*md"
  post-render:
    # - "rsync --recursive --prune-empty-dirs --copy-links --safe-links static/. _site/"
    - "cp -r static/. docs/"

website:
  title: "Arun Kumar Kantheti"
  site-url: https://kirar2004.github.io/Mind-In-Motion
  repo-url: https://github.com/kirar2004/Mind-In-Motion
  repo-actions:
    - source
    - edit
    - issue
  twitter-card:
    creator: "@kirar2004"
    site: "@kirar2004"
    card-style: summary_large_image
    image: social-default.png
  open-graph: true
  navbar:
    title: Mind In Motion
    background: light
    right:
      - text: Blog
        href: blog/index.qmd
      - text: Projects
        href: project/index.qmd
      - text: Talks
        href: talk/index.qmd
      - text: About
        href: about/index.qmd
      - icon: github
        href: https://github.com/kirar2004
      - icon: linkedin
        href: https://www.linkedin.com/in/kirar2004

  page-footer:
    border: false
    background: light
    left: >-
       © {{< now year >}} Arun Kumar Kantheti
    right: >-
      <a class="link-dark me-1" href="/colophon">Made with 💙</a>
    center: >-
      <a class="link-dark" href="https://x.com/kirar2004" title="twitter-x" target="_blank" rel="noopener">{{< fa brands twitter >}}</a>
      <a class="link-dark" href="https://www.linkedin.com/in/kirar2004" title="linkedin" target="_blank" rel="noopener">{{< fa brands linkedin>}}</a>
      <a class="link-dark" href="http://orcid.org/0000-0003-3150-0254" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>

format:
  html:
    theme:
      light:
        - zephyr
        - _assets/styles-elm-light.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
      dark:
        - _assets/zephyr-dark.scss
        - _assets/styles-elm-dark.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
    css:
      - _assets/panelset-extras.css
    highlight-style:
      light: _assets/syntax-elm-light.theme
      dark: _assets/syntax-elm-dark.theme
    code-block-bg: false
    include-in-header:
      text: <script src="https://cdn.counter.dev/script.js" data-id="10454114-dc3f-4c23-a4da-87e7f2c7c58d" data-utcoffset="-4"></script>

execute:
  freeze: auto
